Karadag.Northwind.MvcWebUI/View Components/CategoryListViewComponent.cs
using Karadag.Northwind.Business.Abstract;
using Karadag.Northwind.MvcWebUI.Models;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Karadag.Northwind.MvcWebUI.View_Components
{
    public class CategoryListViewComponent : ViewComponent
    {
        ICategoryService _categoryService;
        public CategoryListViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public ViewViewComponentResult Invoke() {

            var model = new CategoryListViewModel
            {
                Categories = _categoryService.GetAll(),
                CurrentCategory = Convert.ToInt32(HttpContext.Request.Query["category"])
            };
            return View(model);
        }
    }
}

Karadag.Northwind.MvcWebUI/Views/_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link href="@Url.Content("~/bootstrap/dist/css/bootstrap.css")" rel="stylesheet" />
    <script src="@Url.Content("~/jquery/dist/jquery.min.js")"></script>
    <script src="@Url.Content("~/bootstrap/dist/js/bootstrap.js")"></script>
    <script src="@Url.Content("~/jquery-validation/dist/jquery.validate.js")"></script>
    <script src="@Url.Content("~/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js")"></script>
</head>
<body>
    <div class="col-md-12">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">KARADAG | Admin Panel </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Products Store<span class="sr-only">(current)</span></a>
                    </li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" href="#" aria-disabled="true">test</a>
                        
                    </li>
                </ul>
            </div>
        </nav>
    </div>
    <div class="col-md-12">
        @if (TempData["message"] != null) {
            <div class="alert alert-info" role="alert">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
    <div class="col-md-12">
        Footer
    </div>

</body >
</html >

Karadag.Northwind.MvcWebUI/Views/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link href="@Url.Content("~/bootstrap/dist/css/bootstrap.css")" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="@Url.Content("~/bootstrap/dist/js/bootstrap.js")"></script>
</head>
<body>
    <div class="col-md-12">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">KARADAG</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Features</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Pricing</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
    <div class="col-md-2">
        @await Component.InvokeAsync("CategoryList")
    </div>
    <div class="col-md-10">
        @if (TempData["message"] != null) {
            <div class="alert alert-info" role="alert">@TempData["message"]</div>
        }
        @RenderBody()
    </div>
    <div class="col-md-12">
        Footer
    </div>

</body >
</html >